### ISSUE TITLE
Time to archive this?

### ISSUE THREAD

**Issue by abea** [punkave/albedo#10]
It's throwing package vulnerability warning messages.

**Comment by mkopinsky** [comment]
Are you using it? It's probably possible to update dependencies so the warnings go away. I don't have immediate plans to work on this, but a PR would definitely be welcomed.

**Comment by abea** [comment]
I don't know of anyone still using it. P'unk Ave hasn't in years, as far as I'm aware. There's not energy behind this. I do see that the vulnerability fixes are minor versions, so I'll turn on the automated updates for now.

**Comment by abea** [comment]
I ran the updates but am not able to run the test for some reason. There's no real output from Mocha. Maybe it's a versioning issue between my new Node and these old versions. I don't have much reason to take this further. If no one wants to pick this up to maintain I think it should be archived.

Archiving would still allow people to fork and download it. It would simply stop the warning messages and communicate that this isn't in active development. It could be un-archived if someone wants to pick up maintenance.

**Comment by mkopinsky** [comment]
As far as I know, Punk Ave only ever used this for one project, which I am now the lead developer on. We use it in production, but I'm planning on (at some point) moving away from albedo/node to something more closely aligned with the rest of our tech stack. Until then, upgrading versions makes sense.

The test suite doesn't do much - the real test is to run it in a prod-like context and see if it still works. I hope to do that within the next few weeks, I just don't have time this week.

**Comment by mkopinsky** [comment]
BTW, thanks for bringing this to my attention!

**Comment by mkopinsky** [comment]
Actually, I just realized I'm using our fork at https://github.com/waytohealth/albedo instead of this repo directly. The dependency issues apply to the fork as well obviously, but I agree with @abea that this repo should be archived.

**Comment by abea** [comment]
I'll go ahead and do that.
